name: async_list_view
description: Displays a scrollable list of items lazily fetched from an asynchronous data source.
version: 1.0.1
homepage: 'https://github.com/caseycrogers/async_list_view'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.25.0'

dependencies:
  flutter:
    sdk: flutter
  stream_summary_builder: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: