name: async_list_view
description: A wrapper around [StreamSummaryBuilder] and [ListView] that displays a scrollable list of items lazily fetched from an asynchronous data source.
version: 0.0.1-dev.2
homepage: 'https://github.com/caseycrogers/async_list_view'

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  stream_summary_builder: ^0.1.0-dev.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: